### PR TITLE
Replace minus sign with underscore in all *.py file names

### PR DESCRIPTION
**Pull request by Gebon**
Am I right understood this issue?
#22

### CODE REVIEW

**Comment by rougier** [comment]
Yes !  Thanks.
Could you also change in the text as well ?

**Comment by Gebon** [comment]
Of course

**Comment by Gebon** [comment]
@rougier done

**Comment by Gebon** [comment]
Damn, I forgot to change imports in scripts

**Comment by rougier** [comment]
Many thanks !

**Pull request merged**
